INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('1', 'alessandrokraemer@gmail.com', 'A. Kraemer');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('2', 'chavesana@gmail.com', 'Ana Chaves Steinmacher');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('3', 'andreschwerz@gmail.com', 'Andre Schwerz');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('4', '4', 'A. Kawamoto');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('5', '5', 'Aretha');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('6', '6', 'Diego');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('7', '7', 'Filipe');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('8', '8', 'Frank');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('9', '9', 'I. Stein');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('10', '10', 'I. Wiese');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('11', '11', 'Ivanilton');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('12', '12', 'J. Foleiss');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('13', '13', 'Lúcio');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('14', '14', 'Luiz Arthur');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('15', '15', 'Marco Graciotto');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('16', '16', 'M. Silvano');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('17', '17', 'Narci');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('18', '18', 'Paulo Cesar');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('19', '19', 'Paulo Sabo');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('20', '20', 'Radames');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('21', '21', 'Rafael Liberato');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('22', '22', 'Reginaldo Ré');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('23', '23', 'R. Campiolo');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('24', '24', 'R. Hubner');
INSERT INTO `estagio_v01`.`pessoa` (`id_pessoa`, `email_pessoa`, `nome_pessoa`) VALUES ('25', '25', 'RAG');
