SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS `ExemploJPA01` ;
CREATE SCHEMA `ExemploJPA01` ;

GRANT ALL PRIVILEGES ON ExemploJPA01.* TO radames@localhost IDENTIFIED BY 'lageado' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON ExemploJPA01.* TO radames@'%' IDENTIFIED BY 'lageado' WITH GRANT OPTION;
FLUSH PRIVILEGES;

USE ExemploJPA01;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

